In [306]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

# VIF - variation inflation factor 
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [307]:
df = pd.read_csv("Bengaluru_House_Data.csv")

In [308]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [309]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [310]:
df.shape

(13320, 9)

In [311]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [312]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [313]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [314]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [315]:
# remove unnecessary columns [keep only-total_sqft,bath,bhk-2(size),,price,]
df = df[['total_sqft','bath','size','price']].copy()

In [316]:
df

      total_sqft  bath       size   price
0           1056   2.0      2 BHK   39.07
1           2600   5.0  4 Bedroom  120.00
2           1440   2.0      3 BHK   62.00
3           1521   3.0      3 BHK   95.00
4           1200   2.0      2 BHK   51.00
...          ...   ...        ...     ...
13315       3453   4.0  5 Bedroom  231.00
13316       3600   5.0      4 BHK  400.00
13317       1141   2.0      2 BHK   60.00
13318       4689   4.0      4 BHK  488.00
13319        550   1.0      1 BHK   17.00

[13320 rows x 4 columns]

In [317]:
# now convert size into bhk
df.rename(columns = {'size':'bhk'},inplace= True)

In [318]:
df

      total_sqft  bath        bhk   price
0           1056   2.0      2 BHK   39.07
1           2600   5.0  4 Bedroom  120.00
2           1440   2.0      3 BHK   62.00
3           1521   3.0      3 BHK   95.00
4           1200   2.0      2 BHK   51.00
...          ...   ...        ...     ...
13315       3453   4.0  5 Bedroom  231.00
13316       3600   5.0      4 BHK  400.00
13317       1141   2.0      2 BHK   60.00
13318       4689   4.0      4 BHK  488.00
13319        550   1.0      1 BHK   17.00

[13320 rows x 4 columns]

In [319]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_sqft  13320 non-null  object
 1   bath        13247 non-null  float64
 2   bhk         13304 non-null  object
 3   price       13320 non-null  float64
dtypes: float64(2), object(2)
memory usage: 416.4+ KB

In [320]:
# change 2 BHK -- 2 , 3BHK ---3
df["bhk"] = df["bhk"].str.extract(r"(\d+)")

In [321]:
df['bhk']

0        2
1        4
2        3
3        3
4        2
        ..
13315    5
13316    4
13317    2
13318    4
13319    1
Name: bhk, Length: 13320, dtype: object

In [322]:
# now change the data type
df['bhk'] = pd.to_numeric(df['bhk'],errors = 'coerce')

In [323]:
df['total_sqft'] = pd.to_numeric(df['total_sqft'],errors = 'coerce')

In [324]:
df.info() # now data type changed successfully of bhk , total sqft

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_sqft  13073 non-null  float64
 1   bath        13247 non-null  float64
 2   bhk         13304 non-null  float64
 3   price       13320 non-null  float64
dtypes: float64(4)
memory usage: 416.4 KB

In [325]:
df

       total_sqft  bath  bhk   price
0          1056.0   2.0  2.0   39.07
1          2600.0   5.0  4.0  120.00
2          1440.0   2.0  3.0   62.00
3          1521.0   3.0  3.0   95.00
4          1200.0   2.0  2.0   51.00
...           ...   ...  ...     ...
13315      3453.0   4.0  5.0  231.00
13316      3600.0   5.0  4.0  400.00
13317      1141.0   2.0  2.0   60.00
13318      4689.0   4.0  4.0  488.00
13319       550.0   1.0  1.0   17.00

[13320 rows x 4 columns]

In [326]:
df.isnull().sum()

total_sqft    247
bath           73
bhk            16
price           0
dtype: int64

In [327]:
# now removing missing values 
df = df[['total_sqft','bath','bhk','price']].dropna()

In [328]:
df

       total_sqft  bath  bhk   price
0          1056.0   2.0  2.0   39.07
1          2600.0   5.0  4.0  120.00
2          1440.0   2.0  3.0   62.00
3          1521.0   3.0  3.0   95.00
4          1200.0   2.0  2.0   51.00
...           ...   ...  ...     ...
13315      3453.0   4.0  5.0  231.00
13316      3600.0   5.0  4.0  400.00
13317      1141.0   2.0  2.0   60.00
13318      4689.0   4.0  4.0  488.00
13319       550.0   1.0  1.0   17.00

[13057 rows x 4 columns]

In [329]:
# cheking missing values removes or not -- handle missing values
df.isnull().sum()

total_sqft    0
bath          0
bhk           0
price         0
dtype: int64

In [330]:
# now calculate --- VIF(varience inflation factor )
x =df[['total_sqft','bath',	'bhk','price']]
vif = pd.DataFrame()
vif['feature'] = x.columns
vif['vif'] = [variance_inflation_factor(x.values,i) for i in range(x.shape[1])]
print(vif)

      feature        vif
0  total_sqft   3.651113
1        bath  27.992713
2         bhk  26.427588
3       price   2.483968

In [331]:
# Now Training the model
X = df[['total_sqft','bath','bhk']]
y = df['price']

In [332]:
# Train the model
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [333]:
# now creating the model
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error

In [350]:
#OLS/Linear regression 
ols = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])

In [352]:
# ridge
ridge = Pipeline([
    ("scaler", StandardScaler()),
    ("model", Ridge(alpha=1.0))
])

In [354]:
# lasso
lasso = Pipeline([
    ("scaler", StandardScaler()),
    ("model", Lasso(alpha=0.1, max_iter=10000))
])

In [356]:
models = {
    'OLS':OLS,
    'Ridge':ridge,
    "Lasso":lasso
}

In [362]:
print(type(models))
print(models)

<class 'dict'>
{'OLS': Pipeline(steps=[('scaler', StandardScaler(), ('model', LinearRegression()))]), 'Ridge': Pipeline(steps=[('scaler', StandardScaler()), ('model', Ridge())]), 'Lasso': Pipeline(steps=[('scaler', StandardScaler()),
                ('model', Lasso(alpha=0.1, max_iter=10000))])}

In [368]:
# storing the result 
models = {
    "OLS": ols,
    "Ridge": ridge,
    "Lasso": lasso
}

results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    rmse = np.sqrt(
        mean_squared_error(y_test, predictions)
    )
    results[name] = rmse

print(results)

{'OLS': 112.2803195141861, 'Ridge': 112.27990872672511, 'Lasso': 112.26200143552359}