In [1]:
#Q2.
# Your own data
# Export your Swiggy/Zomato order history, or your UPI statement, or your phone's screen-time as a CSV (or type 30 rows by hand).
# Load it, clean the amount column, and answer: spend per weekday, top 5 merchants, and a line plot of monthly total. 
# Commit it to your repo (remove personal identifiers first).

In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv("daily_spending_30_rows.csv")

In [11]:
df.head()

         date  merchant  amount  screen_time_minutes top_screen_app
0  2026-01-02    Swiggy    ₹245                  417       WhatsApp
1  2026-01-03    Zomato    ₹320                  147      Instagram
2  2026-01-05    Amazon    ₹899                  102       WhatsApp
3  2026-01-08    Swiggy    ₹180                  469        Spotify
4  2026-01-10  Flipkart  ₹1,250                  230         Chrome

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 30 non-null     object
 1   merchant             30 non-null     object
 2   amount               30 non-null     object
 3   screen_time_minutes  30 non-null     int64
 4   top_screen_app       30 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.3+ KB

In [15]:
df.describe()

       screen_time_minutes
count            30.000000
mean            284.366667
std             135.689931
min             102.000000
25%             150.500000
50%             268.000000
75%             412.250000
max             469.000000

In [17]:
df.isnull().sum()

date                   0
merchant               0
amount                 0
screen_time_minutes    0
top_screen_app         0
dtype: int64

In [19]:
#my data is clean

In [23]:
df.shape

(30, 5)

In [25]:
df.head()

         date  merchant  amount  screen_time_minutes top_screen_app
0  2026-01-02    Swiggy    ₹245                  417       WhatsApp
1  2026-01-03    Zomato    ₹320                  147      Instagram
2  2026-01-05    Amazon    ₹899                  102       WhatsApp
3  2026-01-08    Swiggy    ₹180                  469        Spotify
4  2026-01-10  Flipkart  ₹1,250                  230         Chrome

In [45]:
#top 5 merchant 
top_5_merchant  = df.groupby('merchant')['amount'].sum().sort_values(ascending = False).head(5)

In [47]:
top_5_merchant

merchant
Amazon            ₹899₹650₹499₹1,200₹750₹890₹560
Zomato          ₹320₹450₹310₹350₹410₹380₹340₹425
Swiggy      ₹245₹180₹275₹220₹290₹190₹260₹210₹300
Flipkart            ₹1,250₹799₹950₹620₹1,100₹850
Name: amount, dtype: object

In [49]:
#Q2. Monthly total
df.head()

         date  merchant  amount  screen_time_minutes top_screen_app
0  2026-01-02    Swiggy    ₹245                  417       WhatsApp
1  2026-01-03    Zomato    ₹320                  147      Instagram
2  2026-01-05    Amazon    ₹899                  102       WhatsApp
3  2026-01-08    Swiggy    ₹180                  469        Spotify
4  2026-01-10  Flipkart  ₹1,250                  230         Chrome

In [80]:
#2.weekday_sales
weekday_sales_amount = df.groupby(('date'))['amount'].sum()

In [82]:
weekday_sales_amount

date
2026-01-02      ₹245
2026-01-03      ₹320
2026-01-05      ₹899
2026-01-08      ₹180
2026-01-10    ₹1,250
2026-01-12      ₹450
2026-01-15      ₹275
2026-01-18      ₹650
2026-01-20      ₹310
2026-01-22      ₹799
2026-01-25      ₹220
2026-01-28      ₹499
2026-02-02      ₹350
2026-02-05      ₹290
2026-02-08    ₹1,200
2026-02-11      ₹950
2026-02-14      ₹410
2026-02-17      ₹190
2026-02-20      ₹750
2026-02-23      ₹620
2026-03-01      ₹260
2026-03-04      ₹380
2026-03-07      ₹890
2026-03-10    ₹1,100
2026-03-13      ₹210
2026-03-16      ₹340
2026-03-19      ₹560
2026-03-22      ₹850
2026-03-25      ₹300
2026-03-28      ₹425
Name: amount, dtype: object

In [ ]:
#monthly total